# Generated by Django 3.1.5 on 2021-01-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '所有学生', 'verbose_name_plural': '所有学生'},
        ),
    ]
