# Generated by Django 3.1.5 on 2021-01-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210107_1936'),
        ('student', '0004_auto_20210111_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentCourse',
            new_name='StudentCourses',
        ),
        migrations.RenameField(
            model_name='studentcourses',
            old_name='course',
            new_name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='student.StudentCourses', to='course.Course'),
        ),
    ]
