# Generated by Django 3.1.5 on 2021-01-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '所有教师', 'verbose_name_plural': '所有教师'},
        ),
    ]
