# Generated by Django 3.1.5 on 2021-01-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='课程编号')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('max_number', models.IntegerField(verbose_name='课程最大人数')),
                ('cur_number', models.IntegerField(verbose_name='课程当前人数')),
                ('teacher', models.CharField(max_length=50, verbose_name='任课教师')),
                ('time', models.CharField(max_length=50, verbose_name='上课时间')),
                ('location', models.CharField(max_length=50, verbose_name='上课地点')),
                ('introduction', models.CharField(max_length=200, verbose_name='课程介绍')),
            ],
        ),
    ]
