# Generated by Django 3.1.5 on 2021-01-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '所有课程'},
        ),
    ]
