# Generated by Django 3.1.5 on 2021-01-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210107_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '所有课程', 'verbose_name_plural': '所有课程'},
        ),
    ]
